version: "3.9"

services:
  socket:
    container_name: socket-docker
    build: .././MeetMe-Websocket/ 
    volumes:
      - '.././MeetMe-Websocket/:/usr/src/app'
    networks:  
      - meetme
    environment:
      API_PORT: 5002
      MONGO_URL: mongodb+srv://MeetMeUser:Ntw171044.@cluster0.salidj6.mongodb.net/?retryWrites=true&w=majority
      TOKEN_KEY: "H3LloM3ETm33wINneR003Nut069bEWo72"
networks:
  meetme:  
    external: true