version: "3.9"

services:
  socket:
    image: winnerkypt/meetme-socket:latest
    container_name: socket-docker
    volumes:
      - '.././MeetMe-Websocket/:/usr/src/app'
    networks:  
      - meetme
    environment:
      API_PORT: ${API_PORT}
      MONGO_URL: ${MONGO_URL}
      TOKEN_KEY: ${TOKEN_KEY}
networks:
  meetme:  
    external: true